package PipeMon::Model::Pipeline;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PipeMon::Schema::Pipeline',
    
    connect_info => {
        dsn => 'dbi:mysql:database=pipe_human;host=lutra5;port=3322',
        user => 'ottro',
    },
);

=head1 NAME

PipeMon::Model::Pipeline - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PipeMon>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PipeMon::Schema::Pipeline>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Michael Gray

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
