package PipeMon::Model::PipeQueue;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'PipeMon::Schema::PipeQueue',
    
    connect_info => {
        dsn => 'dbi:mysql:database=pipe_queue;host=otterlive;port=3324',
        user => 'ottro',
    },

);

=head1 NAME

PipeMon::Model::PipeQueue - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PipeMon>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PipeMon::Schema::PipeQueue>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Michael Gray

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
